version: '3.8'

services:
    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: observly
            POSTGRES_PASSWORD: postgres

volumes:
    postgres_data:
